preservim/nerdcommenter

plugin/NERD_commenter.vim
As title.
Ref:
* [ember-script](http://emberscript.com/)
* [vim-ember-script](https://github.com/heartsentwined/vim-ember-script)
=> add support for ember-script

plugin/NERD_commenter.vim
As title.
Ref:
* [emblem](http://emblemjs.com/)
* [vim-emblem](https://github.com/heartsentwined/vim-emblem)
=> add support for emblem

plugin/NERD_commenter.vim
I've added an '[idris](http://www.idris-lang.org/)' field to delimiterMap
=> Support for Idris

plugin/NERD_commenter.vim
currently the comment style for stap script is '--' but it seems in correct.
change it to c style
=> change the comment style for systemtap (.stp)

plugin/NERD_commenter.vim
=> Support for Julia

plugin/NERD_commenter.vim
=> remove space at end of appended comment

plugin/NERD_commenter.vim
stan home page: www.mc-stan.org
=> Add support for stan bayesian modeling language

plugin/NERD_commenter.vim
Add mappings for YAML format files, and SLS (SaltStack state files; which are YAML under the hood).
=> Add YAML and Salt state (SLS) comment mapping

plugin/NERD_commenter.vim
Added functions to serve as hooks for saving some specific options before commenting and recovering them afterwards. I found out that folding plugins can be really slow (mainly because each line changed triggers evaluating `foldexpr`), so I set `foldmethod` to `manual`, do the commenting and then recover what was configured.  
The `ignorecase` option was also changed, so I moved both to get a consistent way of saving and recovering options.
=> Adding config state handling before/after line comments

plugin/NERD_commenter.vim
Hello,
Added privoxy files support.
Thanks for this plugin !
=> Added privoxy support

plugin/NERD_commenter.vim
Add support for [Tup][1] buildsystem configuration files
[1]: http://gittup.org/tup/
=> Add support for tupfiles

plugin/NERD_commenter.vim
E.g. for haskell, scheme, scala, lisp, ocaml, sml. Fixes issue #131
Implemented by adding 'nested'/'nestedAlt' keys to the language delimiter defintions.
=> Support automatic real nesting of comments without placeholders, if supported by the language.

plugin/NERD_commenter.vim
(Found in outdated fork on Github network graph.)
=> Add lpc filetype support

plugin/NERD_commenter.vim
(Found in outdated fork on Github network graph.)
=> Add file format and function for identifying commented lines from outside plugin

plugin/NERD_commenter.vim
(Found in outdated fork on Github network graph.)
=> adding hyphy filetype

plugin/NERD_commenter.vim
Just another file type support PR...
=> Add support for augeas file types

plugin/NERD_commenter.vim
Method per this stack overflow thread: http://stackoverflow.com/a/30766542
=> add support for react/jsx comments (Closes #280)

plugin/NERD_commenter.vim
From MiniZinc website (http://www.minizinc.org):
MiniZinc is a free and open-source constraint modeling language. You can use MiniZinc to model constraint satisfaction and optimization problems in a high-level, solver-independent way, taking advantage of a large library of pre-defined constraints. Your model is then compiled into FlatZinc, a solver input language that is understood by a wide range of solvers.
MiniZinc specifications accept both single-line '%' and multi-line '/\*...\*/' comments. It should be a very simple and straightforward merge.
=> Adding support to MiniZinc constraint modeling language.

plugin/NERD_commenter.vim
[Praat](http://www.fon.hum.uva.nl/praat/) is a program for phonetics
research which has a scripting interface.
=> Add support for Praat scripting language

README.md
=> Fix Markdown Format

plugin/NERD_commenter.vim
Faust is a functional programming language for sound synthesis and audio processing: http://faust.grame.fr/
The file extension is **_.dsp_** and the vim filetype is **_faust_**
=> Add support for Faust

plugin/NERD_commenter.vim
Added support for `.scilla`, a language for smart contracts. https://scilla-lang.org/
Academic paper: https://arxiv.org/abs/1801.00687
Scilla is based off `ocaml`
=> feat: added scilla support

plugin/NERD_commenter.vim
=> Added multipart/block comments to SQL filetype

doc/NERD_commenter.txt
Created a fix for my issue [384](https://github.com/scrooloose/nerdcommenter/issues/384).
=> Added help section about the Leader key

plugin/NERD_commenter.vim
=> Change delimiters of CUDA to match the defaults of C/C++

plugin/NERD_commenter.vim
Adrresses all errors, warnings, and style hints produced by vint.
=> Fix vimscript lint issues

.gitignore, doc/NERD_commenter.txt, plugin/NERD_commenter.vim
Added an API so that we can use NerdCommenter plugin to check if a character is inside a comment or not
Useful for developing plugins depending on NerdCommenter
=> Feature: API 'NERDCommentIsCharCommented(line, col)'

LICENSE, doc/NERD_commenter.txt, plugin/NERD_commenter.vim
Closes #217. I'll leave this PR open for a while waiting for any other feedback on that issue or here, but as of my current review I think this would be my vote going forward.
=> Create LICENSE file for CC0

README.md
=> Mention g:NERDCreateDefaultMappings in README.md

plugin/NERD_commenter.vim
[OPA](https://www.openpolicyagent.org/) [Rego](https://www.openpolicyagent.org/docs/latest/policy-language/)
=> Add support for Rego (Open Policy Agent)

plugin/NERD_commenter.vim
`Jsonnet` is a data templating language for app and tool for developers. It is a simple extention of JSON.
Jsonnet website: https://jsonnet.org/
=> Add support for the jsonnet language

plugin/NERD_commenter.vim
Add Support for UC4 Scripts as used by Automic Automation Engine
See docs for details:
https://docs.automic.com/documentation/webhelp/english/AWA/11.2/AE/11.2/All%20Guides/Content/ucabqx.htm
=> Add UC4 Filetype

plugin/NERD_commenter.vim
Add support for commenting hocon files.
[1] https://github.com/lightbend/config/blob/main/HOCON.md#comments
=> Add hocon filetype

README.md
Added directions to install with Vim 8+ packages like nerd tree README says.
=> Add Directions for Vim 8+ Packages

autoload/nerdcommenter.vim
* fix: variables are not set for a new buffer with filetype = s:last_filetype
* remove unused parameter and simplify name
=> fix and refactor SetUpForNewFiletype

autoload/nerdcommenter.vim, plugin/nerdcommenter.vim
=> Fixup autoload system with shims for public functions

autoload/nerdcommenter.vim
https://ziglang.org/documentation/master/#Comments
=> Add support for Zig

autoload/nerdcommenter.vim
=> Add support for Svelte

autoload/nerdcommenter.vim
=> Prevent caching of buffer commentstring

autoload/nerdcommenter.vim
See https://github.com/google/cel-spec.
=> Add support for CEL

autoload/nerdcommenter.vim
Added vcl (Varnish Configuration Language)
See. https://www.varnish-software.com/developers/tutorials/varnish-configuration-language-vcl/#comments
=> Add support for VCL

autoload/nerdcommenter.vim
=> add support for jq

autoload/nerdcommenter.vim
Just noticed Dart comments weren't working! Thanks for your work supporting this plugin.
=> Add Dart to supported languages

doc/nerdcommenter.txt
fix title number error in chapter-4
=> fix: title number error in chapter-4

autoload/nerdcommenter.vim
Reference: https://github.com/taskjuggler/TaskJuggler
=> feat: add taskjuggler
