plugin/NERD_commenter.vim

according to python pep8 document, we need to insert a space after '#'.

according to pep8, we need a space after '#'

---

doc/NERD_commenter.txt
plugin/NERD_commenter.vim

I add a couple of features that I wanted for commenting that others may find useful:
1. an option to set the default alignment value used by commands which don't have a specific intended alignment.  Using this I can specify how I want NERDCommenterToggle to align my comments.
2. a new alignment value, 'start', which indicates that the comment characters should be inserted at index 0 (column 1) of the line.  As a personal convention, when I'm temporarily commenting code out, I prefer my comment delimiters to be at the very start of the line so that I can quickly pick out what comments are temporary vs permanent.
In addition to updating the help file to document these new features, please also note one gotcha where using the 'start' alignment with g:NERDRemoveExtraSpaces can result in the …

Default alignment option + ability to align at index 0.

---

README.md

Missing escape of < and > resulted in missing <space> rendering for NERDToggleComment.

Fix: missing escaping of < and > .

---

plugin/NERD_commenter.vim

Not strictly necessary since the &commentstring option gives valid comment characters (but then, that seems to be true of most other filetypes supported).
(Thanks for an awesome plugin, by the way).

Added support for fortran and yaml filetypes

---

plugin/NERD_commenter.vim

Dockerfile spec is @ http://docs.docker.io/en/latest/use/builder/
This allows me to use nerdcommenter when writing Dockerfiles

added Dockerfile comment support

---

plugin/NERD_commenter.vim

'%' is not a comment delimiter for bib files. '//' works fine.

Correct bib comment delimiter.

---

plugin/NERD_commenter.vim

The sshdconfig filetype provider does not set `commentstring`, so
support must be explicitly defined.

Add support for sshdconfig files

---

plugin/NERD_commenter.vim

The motivation here is how Golang's godoc works:
> godoc processes Go source files to extract documentation about the contents of the package. Comments that appear before top-level declarations, **with no intervening newlines,** are extracted along with the declaration to serve as explanatory text for the item.
>
> <cite>https://golang.org/doc/effective_go.html#commentary</cite>
> <cite>http://godoc.org/golang.org/x/tools/cmd/godoc</cite>
E.g. before this PR
```go
// This whole block is commented
// in two separate blocks,
// because there's an empty line
// between the first and second block,
// and if you select until the empty line below,
// it's not commented either
func doSome() {
}
```
For godoc to capture the whole comment block, and associate it with the following function in the …

Add config to allow commenting empty lines (useful for Golang's godoc)

---

plugin/NERD_commenter.vim

Terraform files are used to define different resources. Single line comments use a `#` and multi-line comments use `/* ... */`. For more information, see https://terraform.io/docs/configuration/syntax.html.
For a terraform syntax plugin, see https://github.com/markcornick/vim-terraform.

Add support for terraform files

---

plugin/NERD_commenter.vim

Sile is a typesetter somewhat similar to LaTeX that uses two different
possible input formats. Input can be XML which is already covered or
there is a TeX like input format. The normal file extension for the
latter is .sil.

Add comment syntax for SILE

---

plugin/NERD_commenter.vim

scss [seems to prefer](https://github.com/brigade/scss-lint/blob/5f757444622fbb76bcebaaa7db4fbdfca659ae3f/README.md#what-gets-linted) `//` over `/*` style comments.

updated scss comment style to correspond to the style guide

---

plugin/NERD_commenter.vim

Pull request #100 for Racket undid the Python change, see the difference at https://github.com/scrooloose/nerdcommenter/commit/8d3dcc26a6c6b7cb98669bb6a6f9bdbc23f9e770.
This reapplies the patch from #183.
CC @alerque

Reapply PR #183 for Python comments, PR #100 undid this

---

plugin/NERD_commenter.vim

[Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide#hash-space) prefers a `#` with a space instead of a plain `#`.

updated ruby comment to fit with ruby style guide

---

plugin/NERD_commenter.vim

(Found in outdated fork on Github network graph.)
Note this will mean the Ruby default comment doesn't have a space after it any more, those who prefer that style should set `let g:NERDSpaceDelims = 1`. Also see the discussion in #202 on how to make a better fix for this recurring issue.

Add ruby multiline comment tags

---

doc/NERD_commenter.txt
plugin/NERD_commenter.vim

This somewhat fixes Issue #145.
I have no experience in VimL whatsoever, but this seems to be the proper way to respect the NERD_\<filetype\>_alt_style feature. 
If you agree that this is a valid fix, I'd have no problem creating another commit that updates the documentation.

Implement functionality to chose the alternative comment style

---

plugin/NERD_commenter.vim

Vim included in OS X 10.11.5 has a trouble with the latest version of NERD Commenter:
E118: Too many arguments for function: getbufvar
E15: Invalid expression: getbufvar(1,"NERDCommenterFirstInit", 0)
`getbufvar` accepts only two arguments in Vim 7.3 (at least the one included in OS X 10.11.5), and returns an empty string when the buffer or variable does not exist: `getbufvar({buffer}, {variable})`.
Vim 7.4 has extended the built-in function so that it additionally accepts an optional argument which determines the default return value: `getbufvar({buffer}, {variable}, [, {default}])`. When the third argument is not given and the buffer or variable does not exists, `getbufvar` returns an empty string as before.
`getbufvar({buffer}, {variable})` works in both Vim 7.3 and 7.4, and is …

Use getbufvar in an old-fashioned way for backward compatibility

---

plugin/NERD_commenter.vim

/// are single line documentation comments.

Fix rust Alt comments

---

doc/NERD_commenter.txt
plugin/NERD_commenter.vim

This is useful when editing files like [vim-vue](https://github.com/xream/vim-vue).
An example: [file-ini2-vim](https://gist.github.com/xream/c474a1adffeb6f70daa6a7ddc22386e0#file-init2-vim).
In hook functions, we can change the filetype, comment and change it back.
I could not come up with any better solution. If there's any better solution, please let me know.
Thank you for this wonderful plugin.

Add hook functions for NERDComment and SwitchToAlternativeDelimiters

---

README.md
doc/NERD_commenter.txt
plugin/NERD_commenter.vim

If `g:NERDCommentEmptyLines=1` then it will comment empty line, which is useful when commenting blocks.
When uncommenting it will delete any trailing whitespace.

Allow commenting empty lines given configuration

---

README.md
doc/NERD_commenter.txt
plugin/NERD_commenter.vim

Add option g:NERDTrimTrailingWhitespace to allow deleting trailing
whitespace when uncommenting a line.

Add option to trim trailing whitespace

---

plugin/NERD_commenter.vim

HQL(hive query language) syntax is almost equivalent to SQL.

Add hive filetype

---

plugin/NERD_commenter.vim

when set
```
let g:NERDSpaceDelims = 1
let g:NERDCommentEmptyLines = 1
```
when commet empty lines, there will be one space at the end of the line.
```
it is one line
<empty line>
```
eg: in sexy mode it will be
```
/*
* it is one line
*<space>
*/
```
with this pr it will be
```
/*
* it is one line
*
*/
```

can enable TrimTrailingWhitespace when comment

---

plugin/NERD_commenter.vim

M4 knows about two types of ignoring text.  But the concept to which the GNU M4 manual refers to as ["comments"][0] (i.e., lines prefixed with hash signs) is actually telling the interpreter "ignore this text, but pass it to the output".  Most of the time, people don't want the macro comments in their output, so instead the [`dnl` ("discard to next line") macro][1] is usually used for comments in the document-my-thoughts sense.
[0]: https://www.gnu.org/software/m4/manual/m4.html#Comments
[1]: https://www.gnu.org/software/m4/manual/m4.html#Dnl

add support for M4 macro processor

---

plugin/NERD_commenter.vim

Remove trailing whitespace for top and bottom line when uncommenting a sexy commented block.
Fixes https://github.com/scrooloose/nerdcommenter/issues/268

Remove trailing whitespace for top and bottom line

---

plugin/NERD_commenter.vim

Ansible files are basically YAML with some jinja2 templating, but the commenting is the same as YAML, so a `#` on the left works. This PR adds support for that.
For a syntax plugin I've been using [chase/vim-ansible-yaml](https://github.com/chase/vim-ansible-yaml), but it looks like [pearofducks/ansible-vim](https://github.com/pearofducks/ansible-vim) might be a better choice at this point. Both plugins use the file type `ansible` so this should cover them.

Add support for ansible file type

---

plugin/NERD_commenter.vim

There is gitcommit but not yet a gitignore comment symbol.  I think it may come
in handy for those that define the gitignore filetype.

Add gitignore support

---

plugin/NERD_commenter.vim

Hello!
When trying to uncomment alternative delimeted comment (with let g:NERDSpaceDelims = 1)
right space don't recognized, cuz s:Mutltipart() checking only primary delims.

Fix removing space when uncommenting spaced AltDelims multipart comment

---

plugin/NERD_commenter.vim

Technically the minimum necessary syntax for block comments requires
only a single hyphen (`-}`, `{-`), but I have found that using a double
hyphen plays a bit more nicely with the elmcast/elm-vim auto-formatting.
Further, uncommenting when using the single dashes leaves an extra level
of indentation (again, when using elmcast/elm-vim).
-- These are PR (not commit) comments:
Vim auto-removed extra whitespace. Let me know and I can remove those line
changes.
Here's an example of this multi-line comment in action and the resulting
auto-format from elmcast/elm-vim:
```
main : Program Never Model Msg
main =
Html.program
{ init = ( initialModel, Cmd.none )
, view = view
, update = update
, subscriptions = (\model -> Sub.none)
}
```
becomes
```
{--
- main : Program Never Model Msg
- main =
- …
```

Add multi-line comments for Elm

---

doc/NERD_commenter.txt
plugin/NERD_commenter.vim

This adds support for shader_test files in piglit, the open source
test suite for OpenGL implementations such as mesa. More information on
piglit can be found at:
https://piglit.freedesktop.org/

Add support for piglit's shader_test files

---

plugin/NERD_commenter.vim

Add support for [Robot Framework](http://robotframework.org/) test suites.
From the [Robot Framework User Guide](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#rules-for-parsing-the-data):
> When Robot Framework parses the test data, it ignores:
>
> * ...
> * All characters following the hash character (#), when it is the first character of a cell. This means that hash marks can be used to enter comments in the test data.
> * ...
...which in general means that a line starting with `#` is regarded as a comment.
To be used with Vim filetype plugins such as https://github.com/mfukar/robotframework-vim, registering the Vim filetype `robot` .

Add support for Robot Framework files

---

README.md
doc/NERD_commenter.txt
plugin/NERD_commenter.vim

Sometimes I need to comment a paragraph, but the first line is comment.
So I added an option, the default is 0, as before. 
After set to 1, NERDCommenterToggle will detect each line, if there have oneline not be commented, then comment all lines.

add options for NERDCommenterToggle to check all lines

---

plugin/NERD_commenter.vim

using multi-line comments is uncommon in haskell, and it makes more sense to use multiple single line comments rather than multiple mult-line comments. this changes the default behavior from
```haskell
{- foo :: Int -> Int -}
{- foo a = a + 1 -}
{- bar :: Text -> Text -}
{- bar x = x <> "text" -}
```
to
```haskell
-- foo :: Int -> Int
-- foo a = a + 1
-- bar :: Text -> Text
-- bar x = x <> "text"
```

haskell default comment style more idiomatic

---

plugin/NERD_commenter.vim

It's a fix for: https://github.com/scrooloose/nerdcommenter/issues/306

Fix ruby comments, totally broken with =begin and =end

---

plugin/NERD_commenter.vim

Hi, I'm not sure this is a bug or not, but I think my pull request would make a better performance.
Currently, when I set "g:NERDToggleCheckAllLines = 1", if I use `<leader>c<space>`, it would check all my selected lines(including blank lines!), if one of theses lines is not commented, it will comment all lines.
For example:
```Python
```
Note that the second line is blank. If I select line 1 to 3, and press `<leader>c<space>`, then the code will become:
```Python
```
While what I want to do is uncomment line 1 and line 3. I don't think somebody woud like to comment line 1 and line 3 again.
So I made this pull request to let "g:NERDToggleCheckAllLines" not check the blank lines. It should only check the valid lines(I think blank line is not valid lines).
If you think what I changed is …

make g:NERDToggleCheckAllLines not check blank lines

---

doc/NERD_commenter.txt
plugin/NERD_commenter.vim

Add an option: NERDDisableTabsInBlockComm. 1 disables adding tabs before the comment symbols in the block style.
This option is probably related to this open issue: https://github.com/scrooloose/nerdcommenter/issues/288

Add an option: NERDDisableTabsInBlockComm

---

README.md
doc/NERD_commenter.txt

11 years ago, b54d3bb renamed `NERDCom[A-Z]` mappings to `<plug>NERDCommenter[A-Z]` mappings.  (Unknown if intentional.)  But, the docs were never updated.  When README.md was later created, it kept the old `NERDCom[A-Z]` names.
Without these changes, it can be quite confusing to someone trying to setup their own mappings, and having nothing work!  Found a few previous issues that look like they were caused by this confusion.
I don't know if splitting the `NERDCommenterAlign{Left,Both}` tags as in the second commit is customary, but it works and still avoids having two separate help sections.  I don't feel replacing `NERDComAlignedComment` with `NERDCommenterAlignedComment` is the proper fix here, because someone searching for a `NERDCommenterAlign{Left,Both}` tag isn't going to find it. …

Update documentation for 11 year old NERDCommenter[A-Z] style

---

plugin/NERD_commenter.vim

- Sentinel is a new language developed by Hashicorp
- Sentinel supports three types of comments, `#` and `//` for single
line comments and `/* ... */` for multi-line comments as described
in their documentation - https://docs.hashicorp.com/sentinel/language/spec/#comments
- Since sentinel and terraform, .tf extension, are related, the `#`
symbol was chosen to keep in line with the tf single line comment

Adds New Delimiter for Hashicorp Sentinel Files

---

plugin/NERD_commenter.vim

Coccinelle is a tool used for transforming C source code. It
uses the Semantic Patch Language (.cocci files) for doing this.
The conventional notation for commenting in semantic patches
is "//".
Used in conjunction with this plugin:
https://github.com/ahf/cocci-syntax
The cocci filetype is set, following which NERD_commenter can
be used in .cocci files.
Signed-off-by: Jaskaran Singh <jaskaransingh7654321@gmail.com>

Add semantic patch (.cocci) to delimiterMap

---

plugin/NERD_commenter.vim

If `set whichwrap+=l`, `normal! l` may move the cursor to the next line, which breaks  `NERDCommenterInsert`. Instead, we can merge `normal! l` and `startinsert` into `feedkeys('a', 'ni')`. Note that [`normal! a` doesn't work](https://stackoverflow.com/q/11587124).
Another solution is to reset `whichwrap` to default before running `normal! l` but I think feedkeys is simpler.

whichwrap-independent Insert

---

plugin/NERD_commenter.vim

This PR adds support for the nix language, it just uses a single `#` on the left to comment out a line so I've added this to the `delimiterMap`.
The nix language is used by [nixpkgs](https://github.com/NixOS/nixpkgs), [NixOS](https://nixos.org/) and some other Nix-related projects.
Thank you for the plugin! Just trying to get this in so future nix programmers don't have to set `NERDCustomDelimiters`.

Add support for the `nix` language.

---

plugin/NERD_commenter.vim

in the file ```plugin/NERD_commenter.vim``` inside the function s:CommentBlock, the following if...endif statement
```vim
if !s:Multipart() && g:NERDAllowAnyVisualDelims && s:AltMultipart()
let switchedDelims = 1
call s:SwitchToAlternativeDelimiters(0)
endif
```
should be replaced with
```vim
if !s:Multipart() && !g:NERDAllowAnyVisualDelims && s:AltMultipart()
let switchedDelims = 1
call s:SwitchToAlternativeDelimiters(0)
endif
```
since the switch to alternative delimiters 
should occur only if g:NERDAllowAnyVisualDelims = 0

tentative fix of issue #425

---

README.md

Thought I'd drop this in the readme to explain how to mimic comment motions, _a la_ commentary.
See also #315, #260. Thanks for continuing to provide community support for nerdcommenter!

Add a note on binds for text object motions

---

plugin/NERD_commenter.vim

Fixes the type "leftalt" to "leftAlt" for the filetype rmd.

Fix leftAlt for filetype rmd

---

plugin/NERD_commenter.vim

Update to the [Open Policy Agent ](https://www.openpolicyagent.org) comment character. Based on the [policy-language](https://www.openpolicyagent.org/docs/latest/policy-language/), a comment begins with `#`.

Update rego comment to #

---

plugin/NERD_commenter.vim

reproduce issue:
1. open lua file;
2. run ex `let g:NERDCompactSexyComs = 1`;
3. enter visual mode and select multiple lines;
4. `<leader>cs`;
5. `<leader>cu`;
solve this issue by escaping `[` and `]`.

fix: can't uncomment in sexy mode with NERDCompactSexyComs=1 for lua

---

plugin/NERD_commenter.vim

Let nerdcommenter properly comment cypher files.
* [extension recommendation](https://neo4j.com/docs/cypher-manual/current/styleguide/#cypher-styleguide-general-recommendations)
* [comments syntax](https://neo4j.com/docs/cypher-manual/current/syntax/comments/)

Add neo4j cypher filetype

---

plugin/NERD_commenter.vim

<Plug>NERDCommenterComment using block comment on visual block whose
last char is unicode breaks up the unicode char. Example:
a가 → /* a<ea> */<b0><80>
To fix this, add the character's byte length to the index used for
chopping the right part of the text block to be commented.

Fix multibyte character bug in block comment

---

autoload/nerdcommenter.vim

Hi Maintainer
I found that the behavior of the 'g:NERDAllowAnyVisualDelims' option is inconsistent with that described in the document. 
https://github.com/preservim/nerdcommenter/blob/2c87cae76ed88f3b0c957df68c03573ecafa3728/doc/nerdcommenter.txt#L524-L545
PR #440 .
Best Respect.

fix 'g:NERDAllowAnyVisualDelims' behavior

---

autoload/nerdcommenter.vim

After I add a custom keymap likes following segment
```
nmap <silent> <expr> gc nerdcommenter#IsLineCommented(line(".")) ?
\ "\:call nerdcommenter#Comment(1, 'uncomment')<CR>"
\ : "\:call nerdcommenter#Comment(1, 'alignBoth')<CR>"
```
Call the map in a buffer that without any nerdCommenter's comment function been invoked before, vim will complain "E121: Undefined variable: b:NERDCommenterDelims".
Add `nerdcommenter#SetUp` invoke will make vim stop complaining.

Add SetUp call in IsLineCommented function definition

---

autoload/nerdcommenter.vim
plugin/nerdcommenter.vim

* Simplify comment delimiter insertion.
* Remove the code that unnecessarily touches the leading spaces/tabs.
* Fix a bug in which `<Plug>NERDCommenterInsert` inserts the comment
delimiters in a wrong position when `col('.')==1`.
Example: `1|234` (cursor at `|`) → `/* */1234`.
* NOTE: Should avoid `feedkey(.., 'ni')` for inserting comment
delimiters to ensure that `NERDCommenter_after` is called after
inserting the delimiters. `feedkey` only adds the input to the queue,
which will be processed after exiting the script context. On the other
hand, `:normal` and `feedkey(.., 'x')` are eagerly processed.

Simplify and fix NERDCommenterInsert

---

autoload/nerdcommenter.vim

Adding support for cairo language by Starkware: https://www.cairo-lang.org/
There isn't an official ft plugin for it yet, but this is what's being used by the community as of now with the ft being defined as `cairo`
https://github.com/starkware-libs/cairo-lang/tree/master/src/starkware/cairo/lang/ide/vim

Add support for Starkware cairo

---

autoload/nerdcommenter.vim

This change fixes the issue there custom hooks change filetype to change delimiters but nerdcommenter wouldn't respect the changes.
Fixes #479 and adds support towards #17 with custom hooks like in https://github.com/posva/vim-vue/blob/master/readme.md#nerdcommenter

Allow hooks to change filetype and comment deilmiters

---

autoload/nerdcommenter.vim

Closes #491
The fix is quite transparent - just use a regular expression to find the first comment character.

Fix bug for unable to uncomment indented comments in vim files

---

autoload/nerdcommenter.vim

Change `left` and `leftAlt` delimiters to nestable `REM ` (extra space character is required) for security and compatibility reasons. Here is two (the shortest) of the many justifications:
- [tldr](https://stackoverflow.com/a/12407934)
- [generalized](https://stackoverflow.com/a/12408045)

feat(dosbatch): change `dosbatch` delimiters

---

autoload/nerdcommenter.vim

Starkware has released updates to the Cairo language where they replaced the `#` comments with `//` and in the upcoming 1.0 version, they'll support `//` as well as `/* */` equivalent to Rust. 
Cairo 1.0 repository for reference: https://github.com/starkware-libs/cairo

Update starkware cairo comments to latest syntax

---

autoload/nerdcommenter.vim

Recompute `indxLeft` and `indxLeftAlt` after line has changed.
Further on, the code checks if `indxLeftPlace < indxLeft` to determine whether there is a placeholder,
however the `indxLeft` is wrong as it is first computed before the line is uncommented but `indxLeftPlace` is computed after uncommenting.
Related to this PR that was never merged: https://github.com/preservim/nerdcommenter/pull/226
Related issue: https://github.com/preservim/nerdcommenter/issues/68

fix issues with placeholders not being replaced by real comment strings when uncommenting

---

autoload/nerdcommenter.vim
doc/nerdcommenter.txt

I removed some white space.
ref. https://github.com/preservim/nerdcommenter/pull/516#pullrequestreview-1401990485
`w=1` is recommended.
https://github.com/preservim/nerdcommenter/pull/517/files?w=1

chore: format

---

autoload/nerdcommenter.vim

fix #518
The code set the variable `b:NERDCommenterFirstInit` on the current buffer, but access the variable using buffer number 1 - this should be incorrect. Changed to `bufnr()` instead.

Correct use of b:NERDCommenterFirstInit

---

autoload/nerdcommenter.vim

There's an error in vim 8.0:
```
E119: Not enough arguments for function: bufnr
E116: Invalid arguments for function getbufvar(bufnr(),'NERDCommenterFirstInit')
E15: Invalid expression: getbufvar(bufnr(),'NERDCommenterFirstInit')
```
In that version, `bufnr` requires an argument, so pass `"%"`, which means current buffer.

Provide argument for bufnr

---

autoload/nerdcommenter.vim

Adds support for raw HCL files, docs [here](https://developer.hashicorp.com/packer/docs/templates/hcl_templates/syntax#comments).

Add new delimiter for HCL files

---

autoload/nerdcommenter.vim

see: https://alloytools.org/tutorials/online/sidenote-format-comments.html

Add delimiters for Alloy files

---

autoload/nerdcommenter.vim

> The "#" character at start of line (no space at front) can be used to mark this line as a comment line.
https://man7.org/linux/man-pages/man5/pam_env.conf.5.html

Add delimiter for pamenv

---

autoload/nerdcommenter.vim

> Lines starting with // are treated as comments (ignored), as well as all text between /* and */, just like C/C++ comments.
> https://manpages.debian.org/stretch/apt/apt.conf.5.en.html
Used for config `/etc/apt/apt.conf` and configs in `/etc/apt/apt.conf.d/`.

Add delimiter for aptconf

---

autoload/nerdcommenter.vim

Copy the configuration for a file rather than capture by reference.
Due to the logic in the alternative delimiter configurator, which swaps the delimiters when called, every second buffer the script is used swaps the delimiter order in the original config. This leads to incorrect delimiters being used in every second buffer.
This change makes a copy for each buffer so swapping the order will not affect the next loaded buffer.

Fix alternative delimiter usage in alternate buffers
